on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Deploy to GH Pages
        run: |
          git config --global user.email "jimmyjcl753@gmail.com"
          git config --global user.name "ji-mmyliu"
          git remote set-url origin https://${{ secrets.GH_PAGES_TOKEN }}@github.com/Taste-of-Nostalgia/client.git
          npm run deploy
